name: Deploy To Dev
on:
  push:
    branches:
      - dev 
jobs:
  run-artisan-commands:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          port: 65002
          script: |
            cd domains/hotpink-gnu-383634.hostingersite.com/public_html/mapi || exit 1
            cp .env.dev .env
            php artisan --version
            php artisan db:drop-all
            php artisan migrate:subfolders
            php artisan db:seed-all
            php artisan config:cache
            php artisan route:cache
            echo "✅ Dev Environment is Ready at $(date)"